DROP TABLE IF EXISTS audit_events;
DROP TABLE IF EXISTS request_logs;
DROP TABLE IF EXISTS models;
DROP TABLE IF EXISTS providers;
DROP TABLE IF EXISTS api_keys;
DROP TABLE IF EXISTS wallets;
DROP TABLE IF EXISTS users;
