models:

  - id: bfl/flux-2-flex
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    source: auto
    provider_id: bfl
    upstream_id: flux-2-flex
    name: flux-2-flex
    canonical_slug: bfl/flux-2-flex
    context_length: 0
    supported_parameters:
      - max_tokens
      - response_format
      - stop
      - temperature
      - tool_choice
      - tools
      - top_p
    top_provider:
      is_moderated: false

  - id: bfl/flux-2-klein-4b
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    source: auto
    provider_id: bfl
    upstream_id: flux-2-klein-4b
    name: flux-2-klein-4b
    canonical_slug: bfl/flux-2-klein-4b
    context_length: 0
    supported_parameters:
      - max_tokens
      - response_format
      - stop
      - temperature
      - tool_choice
      - tools
      - top_p
    top_provider:
      is_moderated: false

  - id: bfl/flux-2-klein-9b
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    source: auto
    provider_id: bfl
    upstream_id: flux-2-klein-9b
    name: flux-2-klein-9b
    canonical_slug: bfl/flux-2-klein-9b
    context_length: 0
    supported_parameters:
      - max_tokens
      - response_format
      - stop
      - temperature
      - tool_choice
      - tools
      - top_p
    top_provider:
      is_moderated: false

  - id: bfl/flux-2-klein-9b-preview
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    source: auto
    provider_id: bfl
    upstream_id: flux-2-klein-9b-preview
    name: flux-2-klein-9b-preview
    canonical_slug: bfl/flux-2-klein-9b-preview
    context_length: 0
    supported_parameters:
      - max_tokens
      - response_format
      - stop
      - temperature
      - tool_choice
      - tools
      - top_p
    top_provider:
      is_moderated: false

  - id: bfl/flux-2-max
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    source: auto
    provider_id: bfl
    upstream_id: flux-2-max
    name: flux-2-max
    canonical_slug: bfl/flux-2-max
    context_length: 0
    supported_parameters:
      - max_tokens
      - response_format
      - stop
      - temperature
      - tool_choice
      - tools
      - top_p
    top_provider:
      is_moderated: false

  - id: bfl/flux-2-pro
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    source: auto
    provider_id: bfl
    upstream_id: flux-2-pro
    name: flux-2-pro
    canonical_slug: bfl/flux-2-pro
    context_length: 0
    supported_parameters:
      - max_tokens
      - response_format
      - stop
      - temperature
      - tool_choice
      - tools
      - top_p
    top_provider:
      is_moderated: false

  - id: bfl/flux-2-pro-preview
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    source: auto
    provider_id: bfl
    upstream_id: flux-2-pro-preview
    name: flux-2-pro-preview
    canonical_slug: bfl/flux-2-pro-preview
    context_length: 0
    supported_parameters:
      - max_tokens
      - response_format
      - stop
      - temperature
      - tool_choice
      - tools
      - top_p
    top_provider:
      is_moderated: false

  - id: bfl/flux-dev
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0.025'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - image
    enabled: true
    source: auto
    provider_id: bfl
    upstream_id: flux-dev
    name: flux-dev
    canonical_slug: bfl/flux-dev
    context_length: 0
    supported_parameters:
      - max_tokens
      - stop
      - temperature
      - top_p
    top_provider:
      is_moderated: false

  - id: bfl/flux-kontext-max
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0.08'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    source: auto
    provider_id: bfl
    upstream_id: flux-kontext-max
    name: flux-kontext-max
    canonical_slug: bfl/flux-kontext-max
    context_length: 0
    supported_parameters:
      - max_tokens
      - stop
      - temperature
      - top_p
    top_provider:
      is_moderated: false

  - id: bfl/flux-kontext-pro
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0.04'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    source: auto
    provider_id: bfl
    upstream_id: flux-kontext-pro
    name: flux-kontext-pro
    canonical_slug: bfl/flux-kontext-pro
    context_length: 0
    supported_parameters:
      - max_tokens
      - stop
      - temperature
      - top_p
    top_provider:
      is_moderated: false

  - id: bfl/flux-pro-1.0-expand
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0.05'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    source: auto
    provider_id: bfl
    upstream_id: flux-pro-1.0-expand
    name: flux-pro-1.0-expand
    canonical_slug: bfl/flux-pro-1.0-expand
    context_length: 0
    supported_parameters:
      - max_tokens
      - stop
      - temperature
      - top_p
    top_provider:
      is_moderated: false

  - id: bfl/flux-pro-1.0-fill
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0.05'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    source: auto
    provider_id: bfl
    upstream_id: flux-pro-1.0-fill
    name: flux-pro-1.0-fill
    canonical_slug: bfl/flux-pro-1.0-fill
    context_length: 0
    supported_parameters:
      - max_tokens
      - stop
      - temperature
      - top_p
    top_provider:
      is_moderated: false

  - id: bfl/flux-pro-1.0-fill-finetuned
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    source: auto
    provider_id: bfl
    upstream_id: flux-pro-1.0-fill-finetuned
    name: flux-pro-1.0-fill-finetuned
    canonical_slug: bfl/flux-pro-1.0-fill-finetuned
    context_length: 0
    supported_parameters:
      - max_tokens
      - response_format
      - stop
      - temperature
      - tool_choice
      - tools
      - top_p
    top_provider:
      is_moderated: false

  - id: bfl/flux-pro-1.1
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0.04'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - image
    enabled: true
    source: auto
    provider_id: bfl
    upstream_id: flux-pro-1.1
    name: flux-pro-1.1
    canonical_slug: bfl/flux-pro-1.1
    context_length: 0
    supported_parameters:
      - max_tokens
      - stop
      - temperature
      - top_p
    top_provider:
      is_moderated: false

  - id: bfl/flux-pro-1.1-ultra
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0.06'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - image
    enabled: true
    source: auto
    provider_id: bfl
    upstream_id: flux-pro-1.1-ultra
    name: flux-pro-1.1-ultra
    canonical_slug: bfl/flux-pro-1.1-ultra
    context_length: 0
    supported_parameters:
      - max_tokens
      - stop
      - temperature
      - top_p
    top_provider:
      is_moderated: false

  - id: bfl/flux-pro-1.1-ultra-finetuned
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    source: auto
    provider_id: bfl
    upstream_id: flux-pro-1.1-ultra-finetuned
    name: flux-pro-1.1-ultra-finetuned
    canonical_slug: bfl/flux-pro-1.1-ultra-finetuned
    context_length: 0
    supported_parameters:
      - max_tokens
      - response_format
      - stop
      - temperature
      - tool_choice
      - tools
      - top_p
    top_provider:
      is_moderated: false
