models:

  - id: bfl/black_forest_labs/flux-dev
    name: black_forest_labs/flux-dev
    provider_id: bfl
    upstream_id: black_forest_labs/flux-dev
    description: ''
    enabled: true
    context_length: 4096
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'

  - id: bfl/black_forest_labs/flux-kontext-max
    name: black_forest_labs/flux-kontext-max
    provider_id: bfl
    upstream_id: black_forest_labs/flux-kontext-max
    description: ''
    enabled: true
    context_length: 4096
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'

  - id: bfl/black_forest_labs/flux-kontext-pro
    name: black_forest_labs/flux-kontext-pro
    provider_id: bfl
    upstream_id: black_forest_labs/flux-kontext-pro
    description: ''
    enabled: true
    context_length: 4096
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'

  - id: bfl/black_forest_labs/flux-pro
    name: black_forest_labs/flux-pro
    provider_id: bfl
    upstream_id: black_forest_labs/flux-pro
    description: ''
    enabled: true
    context_length: 4096
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'

  - id: bfl/black_forest_labs/flux-pro-1.0-expand
    name: black_forest_labs/flux-pro-1.0-expand
    provider_id: bfl
    upstream_id: black_forest_labs/flux-pro-1.0-expand
    description: ''
    enabled: true
    context_length: 4096
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'

  - id: bfl/black_forest_labs/flux-pro-1.0-fill
    name: black_forest_labs/flux-pro-1.0-fill
    provider_id: bfl
    upstream_id: black_forest_labs/flux-pro-1.0-fill
    description: ''
    enabled: true
    context_length: 4096
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'

  - id: bfl/black_forest_labs/flux-pro-1.1
    name: black_forest_labs/flux-pro-1.1
    provider_id: bfl
    upstream_id: black_forest_labs/flux-pro-1.1
    description: ''
    enabled: true
    context_length: 4096
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'

  - id: bfl/black_forest_labs/flux-pro-1.1-ultra
    name: black_forest_labs/flux-pro-1.1-ultra
    provider_id: bfl
    upstream_id: black_forest_labs/flux-pro-1.1-ultra
    description: ''
    enabled: true
    context_length: 4096
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
