models:

  - id: bfl/flux-dev
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    name: flux-dev
    provider_id: bfl
    upstream_id: flux-dev

  - id: bfl/flux-kontext-max
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    name: flux-kontext-max
    provider_id: bfl
    upstream_id: flux-kontext-max

  - id: bfl/flux-kontext-pro
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    name: flux-kontext-pro
    provider_id: bfl
    upstream_id: flux-kontext-pro

  - id: bfl/flux-pro
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    name: flux-pro
    provider_id: bfl
    upstream_id: flux-pro

  - id: bfl/flux-pro-1.0-expand
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    name: flux-pro-1.0-expand
    provider_id: bfl
    upstream_id: flux-pro-1.0-expand

  - id: bfl/flux-pro-1.0-fill
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    name: flux-pro-1.0-fill
    provider_id: bfl
    upstream_id: flux-pro-1.0-fill

  - id: bfl/flux-pro-1.1
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    name: flux-pro-1.1
    provider_id: bfl
    upstream_id: flux-pro-1.1

  - id: bfl/flux-pro-1.1-ultra
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    name: flux-pro-1.1-ultra
    provider_id: bfl
    upstream_id: flux-pro-1.1-ultra
