models:

  - id: deepseek/deepseek-v4-flash
    pricing:
      prompt: '0.00000014'
      completion: '0.00000028'
      request: '0'
      image: '0'
      input_cache_read: '0.0000000028'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
      tokenizer: DeepSeek
    enabled: true
    source: auto
    provider_id: deepseek
    upstream_id: deepseek-v4-flash
    name: 'DeepSeek: DeepSeek V4 Flash'
    canonical_slug: deepseek/deepseek-v4-flash-20260423
    context_length: 1048576
    supported_parameters:
      - frequency_penalty
      - include_reasoning
      - logit_bias
      - logprobs
      - max_tokens
      - min_p
      - presence_penalty
      - reasoning
      - repetition_penalty
      - response_format
      - seed
      - stop
      - structured_outputs
      - temperature
      - tool_choice
      - tools
      - top_k
      - top_logprobs
      - top_p
    top_provider:
      is_moderated: false
      context_length: 1048576
      max_completion_tokens: 384000
    hugging_face_id: deepseek-ai/DeepSeek-V4-Flash
    links:
      details: /api/v1/models/deepseek/deepseek-v4-flash-20260423/endpoints
    default_parameters:
      temperature: null
      top_p: null
      top_k: null
      frequency_penalty: null
      presence_penalty: null
      repetition_penalty: null

  - id: deepseek/deepseek-v4-pro
    pricing:
      prompt: '0.000000435'
      completion: '0.00000087'
      request: '0'
      image: '0'
      input_cache_read: '0.000000003625'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
      tokenizer: DeepSeek
    enabled: true
    source: auto
    provider_id: deepseek
    upstream_id: deepseek-v4-pro
    name: 'DeepSeek: DeepSeek V4 Pro'
    canonical_slug: deepseek/deepseek-v4-pro-20260423
    context_length: 1048576
    supported_parameters:
      - frequency_penalty
      - include_reasoning
      - logit_bias
      - logprobs
      - max_tokens
      - min_p
      - presence_penalty
      - reasoning
      - repetition_penalty
      - response_format
      - seed
      - stop
      - structured_outputs
      - temperature
      - tool_choice
      - tools
      - top_k
      - top_logprobs
      - top_p
    top_provider:
      is_moderated: false
      context_length: 1048576
      max_completion_tokens: 384000
    hugging_face_id: deepseek-ai/DeepSeek-V4-Pro
    links:
      details: /api/v1/models/deepseek/deepseek-v4-pro-20260423/endpoints
    default_parameters:
      temperature: 1
      top_p: 1
      top_k: null
      frequency_penalty: null
      presence_penalty: null
      repetition_penalty: null
