models:

  - id: moonshot/kimi-k2.5
    pricing:
      prompt: '0.0000006'
      completion: '0.000003'
      request: '0'
      image: '0'
      input_cache_read: '0.0000001'
    architecture:
      input_modalities:
        - text
        - image
        - video
      output_modalities:
        - text
      tokenizer: Other
    enabled: true
    source: auto
    provider_id: moonshot
    upstream_id: kimi-k2.5
    name: Kimi K2.5
    canonical_slug: moonshotai/kimi-k2.5-0127
    context_length: 262144
    supported_parameters:
      - include_reasoning
      - max_completion_tokens
      - max_tokens
      - reasoning
      - stop
      - temperature
      - tool_choice
      - tools
      - top_p
    top_provider:
      is_moderated: false
      context_length: 262144
      max_completion_tokens: 262144
    hugging_face_id: moonshotai/Kimi-K2.5
    default_parameters:
      temperature: null
      top_p: null
      top_k: null
      frequency_penalty: null
      presence_penalty: null
      repetition_penalty: null
    links:
      details: /api/v1/models/moonshotai/kimi-k2.5-0127/endpoints
    description: Kimi's most versatile model featuring a native multimodal architecture that supports both visual and text input, thinking and non-thinking modes, and dialogue and agent tasks. Supports automatic context caching, ToolCalls, JSON Mode, Partial Mode, and internet search.

  - id: moonshot/kimi-k2.6
    pricing:
      prompt: '0.00000095'
      completion: '0.000004'
      request: '0'
      image: '0'
      input_cache_read: '0.00000016'
    architecture:
      input_modalities:
        - text
        - image
        - video
      output_modalities:
        - text
      tokenizer: Other
    enabled: true
    source: auto
    provider_id: moonshot
    upstream_id: kimi-k2.6
    name: kimi-k2.6
    canonical_slug: moonshotai/kimi-k2.6-20260420
    context_length: 262144
    supported_parameters:
      - include_reasoning
      - max_completion_tokens
      - max_tokens
      - reasoning
      - stop
      - temperature
      - tool_choice
      - tools
      - top_p
    top_provider:
      is_moderated: false
      context_length: 262144
      max_completion_tokens: 262144
    hugging_face_id: moonshotai/Kimi-K2.6
    default_parameters:
      temperature: null
      top_p: null
      top_k: null
      frequency_penalty: null
      presence_penalty: null
      repetition_penalty: null
    links:
      details: /api/v1/models/moonshotai/kimi-k2.6-20260420/endpoints

  - id: moonshot/moonshot-v1-128k
    pricing:
      prompt: '0.000002'
      completion: '0.000005'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    source: auto
    provider_id: moonshot
    upstream_id: moonshot-v1-128k
    name: Moonshot V1 128K
    canonical_slug: moonshot/moonshot-v1-128k
    context_length: 131072
    supported_parameters:
      - max_completion_tokens
      - max_tokens
      - stop
      - temperature
      - tool_choice
      - tools
      - top_p
    top_provider:
      is_moderated: false
      context_length: 131072
      max_completion_tokens: 131072

  - id: moonshot/moonshot-v1-128k-vision-preview
    pricing:
      prompt: '0.000002'
      completion: '0.000005'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
        - image
      output_modalities:
        - text
    enabled: true
    source: auto
    provider_id: moonshot
    upstream_id: moonshot-v1-128k-vision-preview
    name: Moonshot V1 128K
    canonical_slug: moonshot/moonshot-v1-128k-vision-preview
    context_length: 131072
    supported_parameters:
      - max_completion_tokens
      - max_tokens
      - stop
      - temperature
      - tool_choice
      - tools
      - top_p
    top_provider:
      is_moderated: false
      context_length: 131072
      max_completion_tokens: 131072

  - id: moonshot/moonshot-v1-32k
    pricing:
      prompt: '0.000001'
      completion: '0.000003'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    source: auto
    provider_id: moonshot
    upstream_id: moonshot-v1-32k
    name: Moonshot V1 32K
    canonical_slug: moonshot/moonshot-v1-32k
    context_length: 32768
    supported_parameters:
      - max_completion_tokens
      - max_tokens
      - stop
      - temperature
      - tool_choice
      - tools
      - top_p
    top_provider:
      is_moderated: false
      context_length: 32768
      max_completion_tokens: 32768

  - id: moonshot/moonshot-v1-32k-vision-preview
    pricing:
      prompt: '0.000001'
      completion: '0.000003'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
        - image
      output_modalities:
        - text
    enabled: true
    source: auto
    provider_id: moonshot
    upstream_id: moonshot-v1-32k-vision-preview
    name: Moonshot V1 32K
    canonical_slug: moonshot/moonshot-v1-32k-vision-preview
    context_length: 32768
    supported_parameters:
      - max_completion_tokens
      - max_tokens
      - stop
      - temperature
      - tool_choice
      - tools
      - top_p
    top_provider:
      is_moderated: false
      context_length: 32768
      max_completion_tokens: 32768

  - id: moonshot/moonshot-v1-8k
    pricing:
      prompt: '0.0000002'
      completion: '0.000002'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    source: auto
    provider_id: moonshot
    upstream_id: moonshot-v1-8k
    name: Moonshot V1 8K
    canonical_slug: moonshot/moonshot-v1-8k
    context_length: 8192
    supported_parameters:
      - max_completion_tokens
      - max_tokens
      - stop
      - temperature
      - tool_choice
      - tools
      - top_p
    top_provider:
      is_moderated: false
      context_length: 8192
      max_completion_tokens: 8192

  - id: moonshot/moonshot-v1-8k-vision-preview
    pricing:
      prompt: '0.0000002'
      completion: '0.000002'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
        - image
      output_modalities:
        - text
    enabled: true
    source: auto
    provider_id: moonshot
    upstream_id: moonshot-v1-8k-vision-preview
    name: Moonshot V1 8K
    canonical_slug: moonshot/moonshot-v1-8k-vision-preview
    context_length: 8192
    supported_parameters:
      - max_completion_tokens
      - max_tokens
      - stop
      - temperature
      - tool_choice
      - tools
      - top_p
    top_provider:
      is_moderated: false
      context_length: 8192
      max_completion_tokens: 8192

  - id: moonshot/moonshot-v1-auto
    pricing:
      prompt: '0.000002'
      completion: '0.000005'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    source: auto
    provider_id: moonshot
    upstream_id: moonshot-v1-auto
    name: moonshot-v1-auto
    canonical_slug: moonshot/moonshot-v1-auto
    context_length: 131072
    supported_parameters:
      - max_completion_tokens
      - max_tokens
      - stop
      - temperature
      - tool_choice
      - tools
      - top_p
    top_provider:
      is_moderated: false
      context_length: 131072
      max_completion_tokens: 131072
