models:

  - id: ollama/cringe:latest
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    source: auto
    provider_id: ollama
    upstream_id: cringe:latest
    name: cringe:latest
    canonical_slug: ollama/cringe:latest
    context_length: 0
    supported_parameters:
      - max_tokens
      - response_format
      - stop
      - temperature
      - tool_choice
      - tools
      - top_p
    top_provider:
      is_moderated: false

  - id: ollama/deepscaler:latest
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    source: auto
    provider_id: ollama
    upstream_id: deepscaler:latest
    name: deepscaler:latest
    canonical_slug: ollama/deepscaler:latest
    context_length: 0
    supported_parameters:
      - max_tokens
      - response_format
      - stop
      - temperature
      - tool_choice
      - tools
      - top_p
    top_provider:
      is_moderated: false

  - id: ollama/deepseek-r1:1.5b
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    source: auto
    provider_id: ollama
    upstream_id: deepseek-r1:1.5b
    name: deepseek-r1:1.5b
    canonical_slug: ollama/deepseek-r1:1.5b
    context_length: 0
    supported_parameters:
      - max_tokens
      - response_format
      - stop
      - temperature
      - tool_choice
      - tools
      - top_p
    top_provider:
      is_moderated: false

  - id: ollama/dolphin-llama3:latest
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    source: auto
    provider_id: ollama
    upstream_id: dolphin-llama3:latest
    name: dolphin-llama3:latest
    canonical_slug: ollama/dolphin-llama3:latest
    context_length: 0
    supported_parameters:
      - max_tokens
      - response_format
      - stop
      - temperature
      - tool_choice
      - tools
      - top_p
    top_provider:
      is_moderated: false

  - id: ollama/dolphin-phi:latest
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    source: auto
    provider_id: ollama
    upstream_id: dolphin-phi:latest
    name: dolphin-phi:latest
    canonical_slug: ollama/dolphin-phi:latest
    context_length: 0
    supported_parameters:
      - max_tokens
      - response_format
      - stop
      - temperature
      - tool_choice
      - tools
      - top_p
    top_provider:
      is_moderated: false

  - id: ollama/llama3.2:3b
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    source: auto
    provider_id: ollama
    upstream_id: llama3.2:3b
    name: llama3.2:3b
    canonical_slug: ollama/llama3.2:3b
    context_length: 0
    supported_parameters:
      - max_tokens
      - response_format
      - stop
      - temperature
      - tool_choice
      - tools
      - top_p
    top_provider:
      is_moderated: false

  - id: ollama/phi3:latest
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    source: auto
    provider_id: ollama
    upstream_id: phi3:latest
    name: phi3:latest
    canonical_slug: ollama/phi3:latest
    context_length: 0
    supported_parameters:
      - max_tokens
      - response_format
      - stop
      - temperature
      - tool_choice
      - tools
      - top_p
    top_provider:
      is_moderated: false

  - id: ollama/small_cringe:latest
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    source: auto
    provider_id: ollama
    upstream_id: small_cringe:latest
    name: small_cringe:latest
    canonical_slug: ollama/small_cringe:latest
    context_length: 0
    supported_parameters:
      - max_tokens
      - response_format
      - stop
      - temperature
      - tool_choice
      - tools
      - top_p
    top_provider:
      is_moderated: false

  - id: ollama/therapist:latest
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    source: auto
    provider_id: ollama
    upstream_id: therapist:latest
    name: therapist:latest
    canonical_slug: ollama/therapist:latest
    context_length: 0
    supported_parameters:
      - max_tokens
      - response_format
      - stop
      - temperature
      - tool_choice
      - tools
      - top_p
    top_provider:
      is_moderated: false

  - id: ollama/tinydolphin:latest
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    source: auto
    provider_id: ollama
    upstream_id: tinydolphin:latest
    name: tinydolphin:latest
    canonical_slug: ollama/tinydolphin:latest
    context_length: 0
    supported_parameters:
      - max_tokens
      - response_format
      - stop
      - temperature
      - tool_choice
      - tools
      - top_p
    top_provider:
      is_moderated: false
