models:

  - id: ollama/codegeex4
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    name: codegeex4
    context_length: 32768
    provider_id: ollama
    upstream_id: codegeex4

  - id: ollama/codegemma
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    name: codegemma
    context_length: 8192
    provider_id: ollama
    upstream_id: codegemma

  - id: ollama/codellama
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    name: codellama
    context_length: 4096
    provider_id: ollama
    upstream_id: codellama

  - id: ollama/deepseek-coder-v2-base
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    name: deepseek-coder-v2-base
    context_length: 8192
    provider_id: ollama
    upstream_id: deepseek-coder-v2-base

  - id: ollama/deepseek-coder-v2-instruct
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    name: deepseek-coder-v2-instruct
    context_length: 32768
    provider_id: ollama
    upstream_id: deepseek-coder-v2-instruct

  - id: ollama/deepseek-coder-v2-lite-base
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    name: deepseek-coder-v2-lite-base
    context_length: 8192
    provider_id: ollama
    upstream_id: deepseek-coder-v2-lite-base

  - id: ollama/deepseek-coder-v2-lite-instruct
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    name: deepseek-coder-v2-lite-instruct
    context_length: 32768
    provider_id: ollama
    upstream_id: deepseek-coder-v2-lite-instruct

  - id: ollama/deepseek-v3.1:671b-cloud
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    name: deepseek-v3.1:671b-cloud
    context_length: 163840
    provider_id: ollama
    upstream_id: deepseek-v3.1:671b-cloud

  - id: ollama/gpt-oss:120b-cloud
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    name: gpt-oss:120b-cloud
    context_length: 131072
    provider_id: ollama
    upstream_id: gpt-oss:120b-cloud

  - id: ollama/gpt-oss:20b-cloud
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    name: gpt-oss:20b-cloud
    context_length: 131072
    provider_id: ollama
    upstream_id: gpt-oss:20b-cloud

  - id: ollama/internlm2_5-20b-chat
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    name: internlm2_5-20b-chat
    context_length: 32768
    provider_id: ollama
    upstream_id: internlm2_5-20b-chat

  - id: ollama/llama2
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    name: llama2
    context_length: 4096
    provider_id: ollama
    upstream_id: llama2

  - id: ollama/llama2-uncensored
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    name: llama2-uncensored
    context_length: 4096
    provider_id: ollama
    upstream_id: llama2-uncensored

  - id: ollama/llama2:13b
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    name: llama2:13b
    context_length: 4096
    provider_id: ollama
    upstream_id: llama2:13b

  - id: ollama/llama2:70b
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    name: llama2:70b
    context_length: 4096
    provider_id: ollama
    upstream_id: llama2:70b

  - id: ollama/llama2:7b
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    name: llama2:7b
    context_length: 4096
    provider_id: ollama
    upstream_id: llama2:7b

  - id: ollama/llama3
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    name: llama3
    context_length: 8192
    provider_id: ollama
    upstream_id: llama3

  - id: ollama/llama3.1
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    name: llama3.1
    context_length: 8192
    provider_id: ollama
    upstream_id: llama3.1

  - id: ollama/llama3:70b
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    name: llama3:70b
    context_length: 8192
    provider_id: ollama
    upstream_id: llama3:70b

  - id: ollama/llama3:8b
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    name: llama3:8b
    context_length: 8192
    provider_id: ollama
    upstream_id: llama3:8b

  - id: ollama/mistral
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    name: mistral
    context_length: 8192
    provider_id: ollama
    upstream_id: mistral

  - id: ollama/mistral-7B-Instruct-v0.1
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    name: mistral-7B-Instruct-v0.1
    context_length: 8192
    provider_id: ollama
    upstream_id: mistral-7B-Instruct-v0.1

  - id: ollama/mistral-7B-Instruct-v0.2
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    name: mistral-7B-Instruct-v0.2
    context_length: 32768
    provider_id: ollama
    upstream_id: mistral-7B-Instruct-v0.2

  - id: ollama/mistral-large-instruct-2407
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    name: mistral-large-instruct-2407
    context_length: 65536
    provider_id: ollama
    upstream_id: mistral-large-instruct-2407

  - id: ollama/mixtral-8x22B-Instruct-v0.1
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    name: mixtral-8x22B-Instruct-v0.1
    context_length: 65536
    provider_id: ollama
    upstream_id: mixtral-8x22B-Instruct-v0.1

  - id: ollama/mixtral-8x7B-Instruct-v0.1
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    name: mixtral-8x7B-Instruct-v0.1
    context_length: 32768
    provider_id: ollama
    upstream_id: mixtral-8x7B-Instruct-v0.1

  - id: ollama/orca-mini
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    name: orca-mini
    context_length: 4096
    provider_id: ollama
    upstream_id: orca-mini

  - id: ollama/qwen3-coder:480b-cloud
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    name: qwen3-coder:480b-cloud
    context_length: 262144
    provider_id: ollama
    upstream_id: qwen3-coder:480b-cloud

  - id: ollama/vicuna
    pricing:
      prompt: '0'
      completion: '0'
      request: '0'
      image: '0'
    architecture:
      input_modalities:
        - text
      output_modalities:
        - text
    enabled: true
    name: vicuna
    context_length: 2048
    provider_id: ollama
    upstream_id: vicuna
